from models import *
from django.middleware.csrf import get_token

def returnAddUserPage(request):
	pageContent = "<script>\n"
	pageContent += "	function validateForm() {\n"
	pageContent += "		var username=document.forms[\"CreateLightForm\"][\"username\"].value;\n"
	pageContent += "		if (username==null || username==\"\") {\n"
	pageContent += "			alert(\"Username must be filled out\");\n"
	pageContent += "			return false;\n"
	pageContent += "		}\n"
	pageContent += "	}\n"
	pageContent += "</script>"
	pageContent += "<form action=\"/Lights/?command=addLightComplete\" method=\"POST\" onsubmit=\"return validateForm()\" name=\"CreateLightForm\">"
	pageContent += "<fieldset>"
	pageContent += "<input type=\"hidden\" name=\"csrfmiddlewaretoken\" value=\"" + get_token(request) + "\"/>"
	pageContent += "<label>Light Name:</label>"
	pageContent += "<input type=\"text\" name=\"lightname\" placeholder=\"Light Name...\" maxlength=\"30\" required pattern=\"[^]{3,30}\">\n"
	pageContent += "<br>"
	pageContent += "<label>Room Name:</label>"
	if request.GET.get('room', 'All') == 'All':
		pageContent += "<input type=\"text\" name=\"roomname\" placeholder=\"Room Name...\" maxlength=\"30\" required pattern=\"[^]{3,30}\">\n"
	else:
		pageContent += "<input type=\"text\" name=\"roomname\" placeholder=\"Room Name...\" value=\"" + request.GET.get('room', 'All').replace("_", " ") + "\" maxlength=\"30\" required pattern=\"[^]{3,30}\">\n"
	pageContent += "<br>"
	pageContent += "<label>Ip Address:</label>"
	pageContent += "<input type=\"text\" name=\"ipaddress\" placeholder=\"Ip Address...\" maxlength=\"30\" required pattern=\"((^|\.)((25[0-5])|(2[0-4]\d)|(1\d\d)|([1-9]?\d))){4}$\">\n"
	pageContent += "<br>"
	pageContent += "<label>Device Type:</label>"
	pageContent += "<select name=\"devicetype\">"
	pageContent += "<option name=\"Arduino\" value=\"Arduino\">Arduino</option>"
	pageContent += "<option name=\"MaxPi\" value=\"MaxPi\">Max's Pi</option>"
	pageContent += "</select>"
	pageContent += "<br>"
	pageContent += "<label>Light Type:</label>"
	pageContent += "<select name=\"lightype\">"
	pageContent += "<option name=\"RGBLight\" value=\"RGBLight\">RGB</option>"
	pageContent += "<option name=\"OnOff\" value=\"OnOff\">On/Off</option>"
	pageContent += "</select>"
	pageContent += "<br>"
	pageContent += "<button type=\"submit\" class=\"btn\">Add User</button>"
	pageContent += "</fieldset>"
	pageContent += "</form>"
	return pageContent
